export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function ProjectsLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="projects-layout">
      {children}
    </div>
  )
}
